### ISSUE TITLE
转码时候需要获得每一行Buffer对象

### ISSUE THREAD

**Issue by yukrain** [leizongmin/node-lei-stream#15]
例如
一个gb18030编码格式的txt文件，在每一行读取的时候，我需要转码。需要用到Buffer对象。
但是on('data')获取到的数据时toString之后的。
具体是这一行，去掉toString后能成功。
https://github.com/leizongmin/node-lei-stream/blob/master/lib/readline.js#L110

不知道有没有更好的方法获得原Buffer对象

**Comment by leizongmin** [comment]
可考虑在`new ReadLineStream(stream, options)`的`options`传入一个`{ toString: false }`来表示不将其转为字符串（默认`{ toString: true }`），这样可以保证接口不变，但又提供一种方式去完成你想要的功能。

你能给我提个 pull request 来实现这个修改么？

**Comment by yukrain** [comment]
已提交

**Comment by leizongmin** [comment]
已合并 https://github.com/leizongmin/node-lei-stream/pull/16 并发布新版本： `lei-stream@1.3.0`
