### ISSUE TITLE
为什么next函数执行了一定次数之后，程序自动退出了呢？

### ISSUE THREAD

**Issue by steelli** [leizongmin/node-lei-stream#19]
function readAndAnalysize2(file) {
   let lines=0;
    // readLineStream第一个参数为ReadStream实例，也可以为文件名
    const s = readLine(fs.createReadStream(file), {
        // 换行符，默认\n
        newline: '\n',
        // 是否自动读取下一行，默认false
        autoNext: false
    });

```
// 读取到一行数据时触发data事件
s.on('data', (data) => {
    console.log(data);
    lines++;
    if (lines < 20) {
        s.next();
    } else {
        console.log("wait!");
    }
});

// 流结束时触发end事件
s.on('end', () => {
    console.log('end');
});

// 读取时出错
s.on('error', (err) => {
    console.error(err);
});

s.next();
```

}

上面这个例子，执行了20次之后，程序自动退出了。预期情况应该是程序在空闲中，等待其他逻辑的执行。
源码我没有找到哪里有process.exit()的调用。

**Comment by leizongmin** [comment]
因为你创建的是读文件流，读到文件尾之后流就已经结束了，由于再没有其他正在进行的任务，所以进程结束，这是Node.js本身很正常的行为。

**Comment by leizongmin** [comment]
如果你想一直监听文件的新增内容，可以使用本模块的tailStream，具体可以先看看这篇文章：http://morning.work/page/2016-07/readable-stream-and-log-files-processing-in-nodejs.html
